version: '3.7'
services:
  mysql_db_container:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  # phpmyadmin_container:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     PMA_HOST: mysql_db_container
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     UPLOAD_LIMIT: 3000000000
  #   ports:
  #     - 8080:80
  #   restart: always

volumes:
  mysql_db_data_container: