# Generated by Django 3.1 on 2020-10-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yasscore',
            name='country_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score', to='places.countryindex'),
        ),
        migrations.AddField(
            model_name='yasscore',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='operators.touroperator'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='country_indexes',
            field=models.ManyToManyField(blank=True, related_name='tour_operators', to='places.CountryIndex'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='headquarters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.country'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='languages',
            field=models.ManyToManyField(blank=True, to='places.Language'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.package'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='parks',
            field=models.ManyToManyField(blank=True, related_name='tour_operators', to='places.Park'),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.country'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='country_indexes',
            field=models.ManyToManyField(blank=True, to='places.CountryIndex'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='itinerary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='operators.itinerary'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='itinerary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.itinerarytype'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='operators.touroperator'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itinerarydaydescription',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_descriptions', to='operators.itinerary'),
        ),
        migrations.AddField(
            model_name='itinerarydaydescription',
            name='parks',
            field=models.ManyToManyField(blank=True, to='places.Park'),
        ),
        migrations.AddField(
            model_name='itineraryactivity',
            name='focus_type',
            field=models.ManyToManyField(blank=True, related_name='itinerary_activities', to='operators.ItineraryFocusType'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='animals',
            field=models.ManyToManyField(blank=True, to='places.Animal'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country_indexes',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='places.CountryIndex'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='places.currency'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='exclusions',
            field=models.ManyToManyField(blank=True, related_name='itineraries_exclusions', to='operators.ItineraryExclusion'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='inclusions',
            field=models.ManyToManyField(blank=True, related_name='itineraries_inclusions', to='operators.ItineraryInclusion'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='itinerary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operators.itinerarytype'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='months',
            field=models.ManyToManyField(to='operators.Month'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='non_safari_focus_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nonsafaris', to='places.activity'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='parks',
            field=models.ManyToManyField(blank=True, related_name='itineraries', to='places.Park'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='safari_focus_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safaris', to='places.activity'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='secondary_focus_activity',
            field=models.ManyToManyField(blank=True, related_name='secondaries', to='places.Activity'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='tour_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itineraries', to='operators.touroperator'),
        ),
    ]
