# Generated by Django 3.1 on 2020-10-03 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_auto_20201003_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItineraryActivity',
        ),
    ]
