# Generated by Django 3.1 on 2020-10-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_delete_itineraryactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarydaydescription',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_descriptions', to='operators.itinerary'),
        ),
    ]
