# Generated by Django 3.1 on 2020-10-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_auto_20201010_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='photos_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
