# Generated by Django 3.1 on 2020-10-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_touroperator_photos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='touroperator',
            name='itinerary_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='meet_and_greet_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='responsiveness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='safari_quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='vehicle_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
