# Generated by Django 3.1 on 2020-10-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
        ('ads', '0002_auto_20201003_1813'),
        ('operators', '0002_auto_20201003_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='photos.photo'),
        ),
        migrations.AddField(
            model_name='ad',
            name='tour_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operators.touroperator'),
        ),
    ]
