# Generated by Django 3.1 on 2020-10-03 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('title_short', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles/%Y/%m/%d')),
                ('image_raw', models.ImageField(blank=True, null=True, upload_to='images/articles_raw/%Y/%m/%d')),
                ('image_caption', models.CharField(blank=True, max_length=1500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('highlights', models.CharField(blank=True, max_length=1500, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('article_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('TRASH', 'Trash')], default='DRAFT', max_length=15)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_description', models.CharField(blank=True, max_length=1500, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=700, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=700, null=True)),
                ('kudu_count', models.IntegerField(default=0)),
                ('visit_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('homepage_text', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
