# Generated by Django 3.1 on 2020-10-03 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='activities',
            field=models.ManyToManyField(blank=True, to='places.Activity'),
        ),
        migrations.AddField(
            model_name='article',
            name='animals',
            field=models.ManyToManyField(blank=True, to='places.Animal'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='country_indexes',
            field=models.ManyToManyField(blank=True, to='places.CountryIndex'),
        ),
        migrations.AddField(
            model_name='article',
            name='parks',
            field=models.ManyToManyField(blank=True, to='places.Park'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
