# Generated by Django 3.1 on 2020-10-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('lodges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodge',
            name='countryIndex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.countryindex'),
        ),
        migrations.AddField(
            model_name='lodge',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.park'),
        ),
    ]
