# Generated by Django 3.1 on 2020-10-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicfieldparkvalue',
            name='dynamic_field',
        ),
        migrations.RemoveField(
            model_name='parkreview',
            name='dynamic_field_values',
        ),
        migrations.RemoveField(
            model_name='touroperatorreview',
            name='dynamic_field_values',
        ),
        migrations.DeleteModel(
            name='DynamicFieldPark',
        ),
        migrations.DeleteModel(
            name='DynamicFieldParkValue',
        ),
    ]
