# Generated by Django 2.2.3 on 2020-03-29 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=3000)),
                ('ip', models.CharField(max_length=1000)),
                ('device_type', models.CharField(max_length=1000)),
                ('browser_type', models.CharField(max_length=1000)),
                ('browser_version', models.CharField(max_length=1000)),
                ('os_type', models.CharField(max_length=1000)),
                ('os_version', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
