# Generated by Django 2.2.3 on 2020-05-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchlog',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
